### ISSUE TITLE
Non HAP codec video possible?

### ISSUE THREAD

**Issue by AntonyNasce-UH** [keijiro/Scrubber#1]
Hey @keijiro - love this demo! I dropped in a movie of my own and then realised it was bound to the HAP codec format...

Is there any technical reason why other codecs wouldn't work with Unity's 'VideoPlayer' component, or does the HapPlayer provide more fine-grain frame control?

**Comment by keijiro** [comment]
The main aim of this project is to use scrubbing (moving a playhead back and forth) for presentation. So, I have to use a codec that allows accurate frame control and backward playback. These features are only available with intra frame codecs (I-frame only compression), and HAP is one of the most major intra frame codecs with real-time playback capability. That's why I use HapPlayer instead of VideoPlayer or other codecs.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
